<response cycle="001" cvus="000" thread="001" suite="Sanity" name="test_sanity" step="001" number="001" type="get" result="Error" url="http://localhost" code="-1" description="Get url" time="1384107172.16" duration="0.000157833099365" traceback='Traceback (most recent call last):&#10;   File "/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py", line 202, in _connect&#10;    cert_file=self._certfile_path, method=rtype)&#10;   File "/usr/lib/python2.7/dist-packages/funkload/PatchWebunit.py", line 360, in WF_fetch&#10;    h.endheaders()&#10;   File "/usr/lib/python2.7/httplib.py", line 969, in endheaders&#10;    self._send_output(message_body)&#10;   File "/usr/lib/python2.7/httplib.py", line 829, in _send_output&#10;    self.send(msg)&#10;   File "/usr/lib/python2.7/httplib.py", line 791, in send&#10;    self.connect()&#10;   File "/usr/lib/python2.7/httplib.py", line 772, in connect&#10;    self.timeout, self.source_address)&#10;   File "/usr/lib/python2.7/socket.py", line 571, in create_connection&#10;    raise err&#10; error: [Errno 111] Connection refused&#10;' />
<testResult cycle="001" cvus="000" thread="001" suite="Sanity" name="test_sanity"  time="1384107172.16" result="Error" steps="1" duration="0.078017950058" connection_duration="0.000157833099365" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/mayank/temp-ankush/sanity/test_Sanity.py&quot;, line 23, in test_sanity&#10;    self.get(self.server_url, description='Get url')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 221, in _connect&#10;    raise SocketError(&quot;Can't load %s.&quot; % url)&#10; error: Can't load http://localhost.&#10;" />
