<response cycle="001" cvus="000" thread="001" suite="Sanity" name="test_sanity" step="001" number="001" type="get" result="Failure" url="/library/librarysite/" code="404" description="Get url" time="1385025522.61" duration="0.0367028713226">
  <headers>
    <header name="date" value="Thu, 21 Nov 2013 09:19:14 GMT" />
    <header name="content-length" value="302" />
    <header name="content-type" value="text/html; charset=iso-8859-1" />
    <header name="connection" value="close" />
    <header name="server" value="Apache/2.2.3 (CentOS)" />
  </headers>
  <body><![CDATA[
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /library/librarysite/ was not found on this server.</p>
<hr>
<address>Apache/2.2.3 (CentOS) Server at intranet.iiit.ac.in Port 80</address>
</body></html>

]]>
  </body>
</response>
<testResult cycle="001" cvus="000" thread="001" suite="Sanity" name="test_sanity"  time="1385025522.61" result="Failure" steps="1" duration="0.0390329360962" connection_duration="0.0367028713226" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/local/lib/python2.7/dist-packages/funkload-1.16.1-py2.7.egg/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/lordinvader/Studies/Presentation-day-code/sanity/test_Sanity.py&quot;, line 23, in test_sanity&#10;    self.get(self.server_url, description='Get url')&#10;   File &quot;/usr/local/lib/python2.7/dist-packages/funkload-1.16.1-py2.7.egg/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/local/lib/python2.7/dist-packages/funkload-1.16.1-py2.7.egg/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/local/lib/python2.7/dist-packages/funkload-1.16.1-py2.7.egg/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /library/librarysite/&#10;HTTP Response 404: Not Found&#10;" />
