<response cycle="001" cvus="000" thread="001" suite="Stress" name="test_stress" step="001" number="001" type="get" result="Failure" url="/Funkload" code="404" description="Get url" time="1384117660.19" duration="0.00197505950928">
  <headers>
    <header name="content-length" value="573" />
    <header name="server" value="Rocket 1.2.4 Python/2.7.4" />
    <header name="connection" value="close" />
    <header name="web2py_error" value="invalid application" />
    <header name="date" value="Sun, 10 Nov 2013 21:07:40 GMT" />
    <header name="content-type" value="text/html; charset=UTF-8" />
  </headers>
  <body><![CDATA[
<html><body><h1>invalid request</h1></body></html><!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx //-->
]]>
  </body>
</response>
<testResult cycle="001" cvus="000" thread="001" suite="Stress" name="test_stress"  time="1384117660.19" result="Failure" steps="1" duration="0.00259685516357" connection_duration="0.00197505950928" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/mayank/temp-ankush/stress/test_Stress.py&quot;, line 21, in test_stress&#10;    self.get(self.server_url, description='Get url')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /Funkload&#10;HTTP Response 404: NOT FOUND&#10;" />
